#
# SPDX-License-Identifier: Apache-2.0
# See LICENSE file for details.
#
# Copyright 2005-2026 the original author or authors.
#

report.spotbugs.column.bug=Bug
report.spotbugs.column.bugs=Bugs
report.spotbugs.column.category=Category
report.spotbugs.column.class=Class
report.spotbugs.column.classes=Classes
report.spotbugs.column.details=Details
report.spotbugs.column.errors=Errors
report.spotbugs.column.files=Files
report.spotbugs.column.line=Line
report.spotbugs.column.missingclasses=Missing Classes
report.spotbugs.column.priority=Priority
report.spotbugs.description=Generates a source code report with the SpotBugs Library.
report.spotbugs.detailslink=https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html
report.spotbugs.effort=Effort is
report.spotbugs.files=Files
report.spotbugs.link=https://spotbugs.github.io/
report.spotbugs.linktitle=The following document contains the results of
report.spotbugs.name=SpotBugs
report.spotbugs.noline=Not available
report.spotbugs.reporttitle=SpotBugs Bug Detector Report
report.spotbugs.summary=Summary
report.spotbugs.threshold=Threshold is
report.spotbugs.versiontitle=SpotBugs Version is

report.spotbugs.aggregate.description=Generates an aggregate SpotBugs report for multi-module projects.
report.spotbugs.aggregate.name=SpotBugs Aggregate
