#
# SPDX-License-Identifier: Apache-2.0
# See LICENSE file for details.
#
# Copyright 2005-2026 the original author or authors.
#

invoker.goals = clean compile spotbugs:spotbugs --no-transfer-progress

# The expected result of the build, possible values are "success" (default) and "failure"
invoker.buildResult = success
