name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'spotbugs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          cache: maven
          distribution: temurin
          java-version: 21
      - name: Analyze with SonarCloud
        run: ./mvnw verify sonar:sonar -B -V -Dsonar.projectKey=com.github.spotbugs:sonar-maven-plugin -Dsonar.organization=spotbugs -Dsonar.host.url=https://sonarcloud.io -Dlicense.skip=true --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
